-- 1. Tạo bảng lưu Trí nhớ AI
CREATE TABLE learned_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Bật bảo mật cho bảng learned_rules (Mọi người có thể đọc/ghi, phù hợp cho nội bộ)
ALTER TABLE learned_rules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Cho phép đọc/ghi rules" ON learned_rules FOR ALL USING (true);


-- 2. Tạo bảng người dùng nội bộ (Custom Users)
CREATE TABLE custom_users (
  username TEXT PRIMARY KEY,
  password TEXT NOT NULL,
  role TEXT NOT NULL
);

-- Thêm 2 tài khoản mặc định
INSERT INTO custom_users (username, password, role) VALUES 
('shrek', '26112025', 'admin'),
('sunnie', '26112025', 'teacher');

-- Bật bảo mật cho bảng custom_users (Chặn đọc trực tiếp từ trình duyệt)
ALTER TABLE custom_users ENABLE ROW LEVEL SECURITY;


-- 3. Tạo hàm kiểm tra đăng nhập (RPC) bảo mật
CREATE OR REPLACE FUNCTION check_login(p_username TEXT, p_password TEXT)
RETURNS TEXT AS $$
DECLARE
  v_role TEXT;
BEGIN
  -- Tìm kiếm tài khoản trùng khớp username và password
  SELECT role INTO v_role 
  FROM custom_users 
  WHERE username = p_username AND password = p_password;
  
  -- Trả về role (admin hoặc teacher), nếu sai sẽ trả về null
  RETURN v_role;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
